### ISSUE TITLE
Selecting SNPs with rs for phasing

### ISSUE THREAD

**Issue by cginer** [cginer/Beagle_Phasing#6]
David, why do we keep only SNPs with rs in the step from VCF to Beagle input format? :/

**Comment by CastellanoED** [comment]
Porq son SNPs mejores!

**Comment by cginer** [comment]
O simplemente más nuevos, que todavía no los han incluído en dbSNP y no les han asignado un #rs.

**Comment by cginer** [comment]
Final decision: We only keep SNPs with #rs.
